# Generated by Django 3.1 on 2020-08-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=300)),
                ('symbol', models.CharField(max_length=300)),
                ('buy_price', models.FloatField(null=True)),
                ('sell_price', models.FloatField(null=True)),
                ('buy_date', models.DateTimeField(default=None, null=True)),
                ('sell_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
